### PR TITLE
[Testing] Fix building on Linux

### PR DESCRIPTION
**Pull request by thrimbor**
This fixes building Xenia on my Arch Linux machine. Without these changes, building throws the following error:
```
==== Building xenia-debug-ui (debug_linux) ====
Creating obj/Linux/Debug/Linux/Debug/xenia-debug-ui
debug_window.cc
/usr/bin/ld: obj/Linux/Debug/Linux/Debug/xenia-vfs-tests/console_app_main_posix.o: in function `main':
/.../xenia/build/../src/xenia/base/console_app_main_posix.cc:21:(.text+0x7d): undefined reference to `cvar::ParseLaunchArguments(int&, char**&, std::basic_string_view<char, std::char_traits<char> >, std::__debug::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)'
/usr/bin/ld: /.../xenia/build/../src/xenia/base/console_app_main_posix.cc:26:(.text+0xcb): undefined reference to `xe::InitializeLogging(std::basic_string_view<char, std::char_traits<char> >)'
/usr/bin/ld: /.../xenia/build/../src/xenia/base/console_app_main_posix.cc:35:(.text+0x180): undefined reference to `xe::ShutdownLogging()'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [xenia-vfs-tests.make:121: bin/Linux/Debug/xenia-vfs-tests] Error 1
make: *** [Makefile:419: xenia-vfs-tests] Error 2
make: *** Waiting for unfinished jobs....
```

I also had to modify the build system to find my system's version of premake5, I can PR that as well if desired.

### CODE REVIEW

**Comment by Shoegzer** [comment]
Thanks, but I tried your PR and it's still failing for me.  Can you have a look at my comment in #2275 regarding building with gcc-14?

**Comment by thrimbor** [comment]
Yeah, there are multiple issues, this only fixes the testing-specific one.

As far as I saw the cxxopts submodule is quite old, and might already have a fix in never versions. I did a cheap workaround by commenting out this line:

https://github.com/xenia-project/xenia/blob/3d30b2eec3ab1f83140b09745bee881fb5d5dde2/premake5.lua#L43

**Comment by Shoegzer** [comment]
Thanks.  What compiler are you using?  I'm sure there's a way to force gcc-13 to avoid the issue I mentioned (perhaps you know off the top?) so I can at least get it to build with your PR.

**Comment by thrimbor** [comment]
Xenia seems to build with clang by default, so clang 18.1.8

**Comment by powerpuffboysz** [comment]
So has anything happened as far as fixing linux builds?

**Comment by hd-genius** [comment]
I just wanted to chime in that this PR and my pr (#2293) does fix the remaining Linux build issues. The issue with the `xenia-vfs-tests` suite is that it is not including the `xenia-base` project to link to. After adding `xenia-base` an error about linking is thrown related to `fmt`. After also adding `fmt` it is successfully building on Ubuntu linux for me.

**Comment by hd-genius** [comment]
After looking at the other PRs it looks like this issues has actually already been fixed, it just hasn't been merged in yet. This change is actually identical to PR #2227.
