### ISSUE TITLE
(Compilation error) Can't build on PopOS 22.04

### ISSUE THREAD

**Issue by hardBSDk** [xenia-project/xenia#2270]
```
discord_rpc.cpp
In file included from ../third_party/discord-rpc/src/discord_rpc.cpp:3:
../third_party/discord-rpc/src/backoff.h:3:10: fatal error: 'algorithm' file not found
#include <algorithm>
         ^~~~~~~~~~~
SStream.c
Linking aes_128
==== Building fmt (debug_linux) ====
Creating obj/Linux/Debug/Linux/Debug/fmt
format.cc
aes.c
In file included from ../third_party/fmt/src/format.cc:8:
../third_party/fmt/include/fmt/format-inl.h:11:10: fatal error: 'cassert' file not found
#include <cassert>
         ^~~~~~~~~
X86ATTInstPrinter.c
1 error generated.
make[1]: *** [discord-rpc.make:182: obj/Linux/Debug/Linux/Debug/discord-rpc/discord_rpc.o] Error 1
make: *** [Makefile:191: discord-rpc] Error 2
make: *** Waiting for unfinished jobs....
os.cc
X86Disassembler.c
In file included from ../third_party/fmt/src/os.cc:13:
../third_party/fmt/include/fmt/os.h:16:10: fatal error: 'cerrno' file not found
#include <cerrno>
         ^~~~~~~~
aes_ctr.c
1 error generated.
```

**Comment by Razzile** [comment]
this is not a xenia issue, your C++ SDK is not installed correctly.
