### ISSUE TITLE
[Linux] Build failure

### ISSUE THREAD

**Issue by Shoegzer** [xenia-project/xenia#2104]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-project/xenia/wiki/FAQ).
- [X] The Xenia build used is from the master branch (not MLBS/AlexVS/Canary/pull requests, etc.)
- [X] This issue isn't for tech support (help with Xenia).
- [X] If this issue occurs in a specific game, I've done analysis to locate the faulty subsystem of the emulator and a potential reason in it.
- [X] I've checked if this issue hasn't already been reported.
- [X] My device meets the minimum requirements: https://github.com/xenia-project/xenia/wiki/Quickstart#system-requirements
- [X] (If building) I have read the building doc: https://github.com/xenia-project/xenia/blob/master/docs/building.md

### Describe what's going wrong

Linux build fails with the following error:

```
In file included from ../src/xenia/ui/imgui_dialog.cc:10:
In file included from ../src/xenia/ui/imgui_dialog.h:16:
../src/xenia/ui/imgui_drawer.h:81:8: error: no template named 'optional' in namespace 'std'
  std::optional<ImGuiKey> VirtualKeyToImGuiKey(VirtualKey vkey);
```
Test information:
* OS: Linux Mint 21.1 (Ubuntu 22.04 base) / kernel 5.15
* CPU: Intel i7-10870H
* Compiler:  gcc-11.3.0
* Bad commit: e55cb737c1b13aaf259cbcd634e0d444e15aa7f0
* Last known good commit: 5fde7c6aa5a2cc3489a1a4069ac48dd4c0fcab57

I can provide a bisect if needed, though it may be related to the recent ImGui update in #2067 (@JoelLinn can you help?) 

### Describe what should happen

Building should succeed.

### If applicable, provide a callstack here, especially for crashes

N/A

### If applicable, upload a logfile and link it here

[build.log](https://github.com/xenia-project/xenia/files/10321941/build.log)

**Comment by JoelLinn** [comment]
Yes, the header is missing an
`#include <optional>`

thanks for reporting, you can open a pr yourself if you wish

**Comment by Shoegzer** [comment]
Done, I'll close this when it's merged. Thanks!

**Comment by georgewoodall82** [comment]
close this

**Comment by Shoegzer** [comment]
Yeah, thought I had when it merged but I guess not
